### ISSUE TITLE
syslogs

### ISSUE THREAD

**Issue by gmarsano** [sharkdp/bat#1605]
If there's one thing I really need bat for, it's to query logs, quickly. But it doesn't automatically recognize the syslog syntax and if I enter it manually (-m=syslog=log) it's pretty poor.

I think it is something that by default should be well polished in a tool of this kind.

**Comment by keith-hall** [comment]
Thanks for the feedback. Can you share a specific example of a syslog which is highlighted suboptimally please and detail your expectations? :) 
It may be that we need to improve the syslog syntax definition we use. Possibly relevant: https://github.com/sharkdp/bat/issues/463

**Comment by gmarsano** [comment]
For example:
I got this from `bat -m=syslog:log /var/log/syslog`:

![Captura de pantalla de 2021-04-04 12-10-42](https://user-images.githubusercontent.com/41755127/113514910-346d7900-953f-11eb-8db0-8522f5493427.png)

And this from vim PaperColor theme colorscheme:

![Captura de pantalla de 2021-04-04 12-10-10](https://user-images.githubusercontent.com/41755127/113514985-bf4e7380-953f-11eb-9c00-779aa881b3cb.png)

As you can see, it helps to recognize numerical values, dates and highlights failures, errors, returns, etc. I think this particular syntax highlighting is a bit excessive, but it still helps a lot to give a quick look at the log.

It would be nice to have something similar, even better, not so blinding, in bat.

**Comment by keith-hall** [comment]
After I quick look, I completely agree that the Syslog highlighting from bat was terrible :sweat_smile: 
It now looks a bit more like this:
![image](https://user-images.githubusercontent.com/11882719/113519912-0cf6ca80-9598-11eb-9b63-2b8e1620dc51.png)

**Comment by gmarsano** [comment]
That looks better. And what about the failures and errors?

**Comment by keith-hall** [comment]
I have updated the PR so that it would highlight errors and failures the same way as invalid syntax in programming languages:
![image](https://user-images.githubusercontent.com/11882719/113617052-9670d000-965e-11eb-9eb5-bcd9dc9b7d2f.png)
I had the idea that highlighting just the word `error` or `failed`/`failure` etc. is cleaner than the full line. Do you agree?

**Comment by gmarsano** [comment]
Good job! For me it's enough. Now you can take a quick look at the log, easily. Improving the default style could be the subject of another issue, if there was someone more creative or an experienced sys admin who could suggest something more objective.

I just want to remind you that for some reason it doesn't recognize the `log` syntax by default when I run it on for example `/ var / log / syslog`. If there is a reason for that, it is not a problem to make an alias or something like that, but I think it is a typical log file and maybe it should recognize it by default.

**Comment by keith-hall** [comment]
I had noticed that previously, the syntax definition was being applied automatically for files called `log` or with a `.log` extension, so my PR addresses that to make it apply for files with a `.syslog` extension (if such a thing is used) or called exactly `syslog`, as it specifically covers only syslog format files. This means log files will likely not be highlighted by default any more after this change. Probably its worth falling back to trying to recognise various date formats and stuff automatically so this syntax definition can still be used for "normal" log files as well. I'll investigate that when I get some spare time.

**Comment by keith-hall** [comment]
I have now pushed up a commit to that PR which enables highlighting of non-syslog log files :)

**Comment by gmarsano** [comment]
Hi again. The highlighting for words `error`, `fail`/`failed`/`failure` (ci) is not working.

**Comment by keith-hall** [comment]
> Hi again. The highlighting for words `error`, `fail`/`failed`/`failure` (ci) is not working.

which color scheme / theme are you using? as [I mentioned in the PR, color schemes may need patching](https://github.com/sharkdp/bat/pull/1606#issue-608601322)

**Comment by timolehto** [comment]
Hello @keith-hall, it seems this still doesn't work or there's been some regression.

Would love to be able to have some level of error highlighting, but I'm not seeing anything. Using default theme, tried some others as well, but it's just not picking up on the errors.

![Image](https://github.com/user-attachments/assets/846b785d-6d5c-44ab-a7f8-787ab092374f)

**Comment by keith-hall** [comment]
@timolehto thanks for drawing my attention to it. I think I know what is wrong, I will try to make a PR to fix it soon

**Comment by timolehto** [comment]
While we're waiting for the fix to get merged and updates reaching users, in case anyone else stumbles here. Here's a quick and dirty hack to simulate error highlighting using `grep` in case your life depends on it 😁:

```
journalctl -g error | head -10 | bat --file-name 'syslog' -f | grep --colour -i -e '^' -e error
```
